[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[build.environment]
  DENO_DEPLOY_TOKEN = ""

[dev]
  command = "deno task serve"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
