name: Publish on Deno Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2

      - name: Build site
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: dropgarden5121
          import-map: "./deno.json"
          entrypoint: "server.ts"